--[[
This file is intended to be run by macro.lua
See macro-readme.html for help and instructions.

You can define more gamekey modules below.
You may put anything on the left except the following reserved characters:
 . W w _ ^ * + - < / > ( ) $ & # !
]]

single={ --for emulators with a single control scheme
	{FCEU,4,{
		{"U","up"},
		{"D","down"},
		{"L","left"},
		{"R","right"},
		{"1","A"},
		{"2","B"},
		{"S","start"},
		{"@","select"},
	}},
	{snes9x,5,{
		{"U","up"},
		{"D","down"},
		{"L","left"},
		{"R","right"},
		{"1","Y"},
		{"2","X"},
		{"3","L"},
		{"4","B"},
		{"5","A"},
		{"6","R"},
		{"S","start"},
		{"@","select"},
	}},
	{vba,1,{
		{"U","up"},
		{"D","down"},
		{"L","left"},
		{"R","right"},
		{"1","B"},
		{"2","A"},
		{"3","L"},
		{"4","R"},
		{"S","start"},
		{"@","select"},
	}},
	{gens,2,{
		{"U","up"},
		{"D","down"},
		{"L","left"},
		{"R","right"},
		{"1","X"},
		{"2","Y"},
		{"3","Z"},
		{"4","A"},
		{"5","B"},
		{"6","C"},
		{"S","start"},
		{"M","mode"},
	}},
	{pcejin,5,{ --PCEjin doesn't work yet because the script has no way of identifying it.
		{"U","Up"},
		{"D","Down"},
		{"L","Left"},
		{"R","Right"},
		{"1","I"},
		{"2","II"},
		{"3","III"},
		{"4","IV"},
		{"5","V"},
		{"6","VI"},
		{"S","Run"},
		{"@","Select"},
	}},
	{pcsx,2,{ --PCSX has broken register functions and no output console.
		{"U","up"},
		{"D","down"},
		{"L","left"},
		{"R","right"},
		{"1","square"},
		{"2","triangle"},
		{"3","r1"},
		{"4","x"},
		{"5","circle"},
		{"6","r2"},
		{"7","l1"},
		{"8","l2"},
		{"S","start"},
		{"@","select"},
	}},
}

FBA={ --for FBA's multiple control schemes
	{"NeoGeo",2,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Button A"},
		{"2","P# Button B"},
		{"3","P# Button C"},
		{"4","P# Button D"},
		{"S","P# Start"},
		{"`","P# Select"},
		{"~","Reset"},
		{"@","Test"},
	}},
	{"PGM",2,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Button 1"},
		{"2","P# Button 2"},
		{"3","P# Button 3"},
		{"4","P# Button 4"},
		{"S","P# Start"},
		{"~","Reset"},
		{"@","Diagnostics 1"},
	}},
	{"Capcom 6-button",2,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Weak Punch"},
		{"2","P# Medium Punch"},
		{"3","P# Strong Punch"},
		{"4","P# Weak Kick"},
		{"5","P# Medium Kick"},
		{"6","P# Strong Kick"},
		{"S","P# Start"},
		{"~","Reset"},
		{"@","Diagnostic"},
	}},
	{"CPS-2 Gem Fighter",2,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Punch"},
		{"2","P# Kick"},
		{"3","P# Special"},
		{"S","P# Start"},
		{"~","Reset"},
		{"@","Diagnostic"},
	}},
	{"CPS-2 Cyberbots",2,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Low Attack"},
		{"2","P# High Attack"},
		{"3","P# Boost"},
		{"4","P# Weapon"},
		{"S","P# Start"},
		{"~","Reset"},
		{"@","Diagnostic"},
	}},
	{"CPS-2 Dungeons & Dragons",4,{
		{"C","P# Coin"},
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Attack"},
		{"2","P# Jump"},
		{"3","P# Select"},
		{"4","P# Use"},
		{"S","P# Start"},
		{"~","Reset"},
		{"@","Diagnostic"},
	}},
	{"Street Fighter 1",2,{
		{"U","P# Up"},
		{"D","P# Down"},
		{"L","P# Left"},
		{"R","P# Right"},
		{"1","P# Button 1"},
		{"2","P# Button 2"},
		{"3","P# Button 3"},
		{"4","P# Button 4"},
		{"5","P# Button 5"},
		{"6","P# Button 6"},
		{"S","P# Start"},
		{"~","Reset"},
	}},
}
