--[[
This file is intended to be run by macro.lua
See macro-readme.html for help and instructions.

You can define more gamekey modules below.
You may put anything on the left except the following reserved characters:
 . W w _ ^ * + - < / > ( ) $ & # !
]]

single = { --for emulators with a single control scheme
--{emu name, nplayers, {{key1 symbol, key1 name}, {key2 symbol, key2 name}, ...}}
	{FCEU, 4, {
		{"U", "up"},
		{"D", "down"},
		{"L", "left"},
		{"R", "right"},
		{"1", "A"},
		{"2", "B"},
		{"S", "start"},
		{"@", "select"},
	}},
	{snes9x, 5, {
		{"U", "up"},
		{"D", "down"},
		{"L", "left"},
		{"R", "right"},
		{"1", "Y"},
		{"2", "X"},
		{"3", "L"},
		{"4", "B"},
		{"5", "A"},
		{"6", "R"},
		{"S", "start"},
		{"@", "select"},
	}},
	{vba, 1, {
		{"U", "up"},
		{"D", "down"},
		{"L", "left"},
		{"R", "right"},
		{"1", "B"},
		{"2", "A"},
		{"3", "L"},
		{"4", "R"},
		{"S", "start"},
		{"@", "select"},
	}},
	{gens, 2, {
		{"U", "up"},
		{"D", "down"},
		{"L", "left"},
		{"R", "right"},
		{"1", "X"},
		{"2", "Y"},
		{"3", "Z"},
		{"4", "A"},
		{"5", "B"},
		{"6", "C"},
		{"S", "start"},
		{"M", "mode"},
	}},
	{pcejin, 5, { --PCEjin doesn't work yet because the script has no way of identifying it.
		{"U", "Up"},
		{"D", "Down"},
		{"L", "Left"},
		{"R", "Right"},
		{"1", "I"},
		{"2", "II"},
		{"3", "III"},
		{"4", "IV"},
		{"5", "V"},
		{"6", "VI"},
		{"S", "Run"},
		{"@", "Select"},
	}},
	{pcsx, 2, {
		{"U", "up"},
		{"D", "down"},
		{"L", "left"},
		{"R", "right"},
		{"1", "square"},
		{"2", "triangle"},
		{"3", "r1"},
		{"4", "x"},
		{"5", "circle"},
		{"6", "r2"},
		{"7", "l1"},
		{"8", "l2"},
		{"S", "start"},
		{"@", "select"},
	}},
}

arcade = { --for FBA/MAME, which have multiple control schemes
--{{driver/parent1 name, parent2 name, ...}, nplayers,
--{{key1 symbol, key1 FBA name, key1 MAME name}, {key2 symbol, key2 FBA name, key2 MAME name}, ...}}
	{{"neodrvr.c", "neogeo"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Button A", "P# Button 1"},
		{"2", "P# Button B", "P# Button 2"},
		{"3", "P# Button C", "P# Button 3"},
		{"4", "P# Button D", "P# Button 4"},
		{"S", "P# Start",    "# Player Start"},
		{"`", "P# Select"},
		{"C", "P# Coin",     "Coin #"},
		{"@", "Test",        "Enter BIOS"},
		{"~", "Reset"},
	}},
	{{"pgm.c", "pgm"}, 4, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Button 1"},
		{"2", "P# Button 2"},
		{"3", "P# Button 3"},
		{"4", "P# Button 4"},
		{"S", "P# Start",      "# Player Start"},
		{"C", "P# Coin",       "Coin #"},
		{"@", "Diagnostics 1"},
		{"~", "Reset"},
	}},
	{{"sf", "sftm", "sfex", "sfexp", "sfex2", "sfex2p"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Button 1"},
		{"2", "P# Button 2"},
		{"3", "P# Button 3"},
		{"4", "P# Button 4"},
		{"5", "P# Button 5"},
		{"6", "P# Button 6"},
		{"S", "P# Start"},
		{"C", "Coin #"},
		{"~", "Reset"},
	}},
	{{"sf2", "sf2ce", "sf2hf",
		"ssf2", "ssf2t", "hsf2", "sfa", "sfa2", "sfa3", "sfz2al",
		"sfiii", "sfiii2", "sfiii3", "redearth", "jojo", "jojoba",
		"xmcota", "xmvsf", "msh", "mshvsf", "mvsc", "dstlk", "nwarr", "vsav", "vhunt2", "vsav2"},
	2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Weak Punch",   "P# Button 1"},
		{"2", "P# Medium Punch", "P# Button 2"},
		{"3", "P# Strong Punch", "P# Button 3"},
		{"4", "P# Weak Kick",    "P# Button 4"},
		{"5", "P# Medium Kick",  "P# Button 5"},
		{"6", "P# Strong Kick",  "P# Button 6"},
		{"S", "P# Start",        "# Player Start"},
		{"C", "P# Coin",         "Coin #"},
		{"@", "Diagnostic",      "Service Mode"},
		{"~", "Reset"},
	}},
	{{"ringdest"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Hold",         "P# Button 1"},
		{"2", "P# Weak punch",   "P# Button 2"},
		{"3", "P# Strong punch", "P# Button 3"},
		{"5", "P# Weak kick",    "P# Button 5"},
		{"6", "P# Strong kick",  "P# Button 6"},
		{"S", "P# Start",        "# Player Start"},
		{"C", "P# Coin",         "Coin #"},
		{"@", "Diagnostic",      "Service Mode"},
		{"~", "Reset"},
	}},
	{{"cybots"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Low Attack",  "P# Button 1"},
		{"2", "P# High Attack", "P# Button 2"},
		{"3", "P# Boost",       "P# Button 3"},
		{"4", "P# Weapon",      "P# Button 4"},
		{"S", "P# Start",       "# Player Start"},
		{"C", "P# Coin",        "Coin #"},
		{"@", "Diagnostic",     "Service Mode"},
		{"~", "Reset"},
	}},
	{{"sgemf"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Punch",   "P# Button 1"},
		{"2", "P# Kick",    "P# Button 2"},
		{"3", "P# Special", "P# Button 3"},
		{"S", "P# Start",   "# Player Start"},
		{"C", "P# Coin",    "Coin #"},
		{"@", "Diagnostic", "Service Mode"},
		{"~", "Reset"},
	}},
	{{"avsp"}, 3, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Shot",    "P# Button 1"},
		{"2", "P# Attack",  "P# Button 2"},
		{"3", "P# Jump",    "P# Button 3"},
		{"S", "P# Start",   "# Player Start"},
		{"C", "P# Coin",    "Coin #"},
		{"@", "Diagnostic", "Service Mode"},
		{"~", "Reset"},
	}},
	{{"ddtod", "ddsom"}, 4, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Attack",  "P# Button 1"},
		{"2", "P# Jump",    "P# Button 2"},
		{"3", "P# Select",  "P# Button 3"},
		{"4", "P# Use",     "P# Button 4"},
		{"S", "P# Start",   "# Player Start"},
		{"C", "P# Coin",    "Coin #"},
		{"@", "Diagnostic", "Service Mode"},
		{"~", "Reset"},
	}},
	{{"megaman", "megaman2"}, 2, {
		{"U", "P# Up"},
		{"D", "P# Down"},
		{"L", "P# Left"},
		{"R", "P# Right"},
		{"1", "P# Fire",    "P# Button 1"},
		{"2", "P# Jump",    "P# Button 2"},
		{"3", "P# Select",  "P# Button 3"},
		{"S", "P# Start",   "# Player Start"},
		{"C", "P# Coin",    "Coin #"},
		{"@", "Diagnostic", "Service Mode"},
		{"~", "Reset"},
	}},
}
